# vim: set tabstop=2 softtabstop=0 expandtab shiftwidth=2:
# This config file will automatically be updated, as long
# as there are no incompatible changes between versions.
# This means that additional comments will not be preserved!

# The language for this module. The corresponding language file must be named
# lang-{lang}.yml. Specifying 'inherit' will load the value set for vane-core.
# Default: "inherit"
lang: "inherit"

# The module will only add functionality if this is set to true.
# Default: true
enabled: true

# Enable plugin metrics via bStats. You can opt-out here or via the global bStats
# configuration. All collected information is completely anonymous and publicly
# available.
# Default: true
metrics_enabled: false

blue_map:
  # Enable BlueMap integration to show player spawnpoints (beds).
  # Default: true
  enabled: false

  # If the marker set should be hidden by default.
  # Default: false
  hide_by_default: false

dynmap:
  # Enable dynmap integration. Player spawnpoints (beds) will then be shown on a
  # separate dynmap layer.
  # Default: true
  enabled: false

  # If the layer should be hidden by default.
  # Default: false
  layer_hide: false

  # Layer ordering priority.
  # Valid values: [0,)
  # Default: 25
  layer_priority: 25

  # The dynmap marker icon.
  # Default: "house"
  marker_icon: "house"

# The interpolation time in ticks for a smooth change of time.
# Valid values: [0,1200]
# Default: 100
interpolation_ticks: 100

# The percentage of sleeping players required to advance time.
# Valid values: [0.0,1.0]
# Default: 0.5
sleep_threshold: 0.5

# The target time in ticks to advance to. 1000 is just after sunrise.
# Valid values: [0,12000]
# Default: 1000
target_time: 1000

# DO NOT CHANGE! The version of this config file. Used to determine if the config
# needs to be updated.
version: 3
